---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in wchrisjohnson/ansible-osx/test.yml"

    - name: get time from ansible-osx/modules
      action: time
      register: playbook_time

    - name: print time from ansible-osx/modules
      debug: msg="time {{playbook_time.time}}"
  
